name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Triggers the pipeline on every push to the main branch
env:
  IMAGE_NAME: shrijandra/hello-app
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Login to Quay.io
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}


