name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Triggers the pipeline on every push to the main branch
env:
  REGISTRY_URL: quay.io
  IMAGE_NAME: shrijandra/hello-app-singlestage
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v6

    # MANDATORY FOR SINGLE-STAGE: Set up Java and Maven on the runner
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven' # Automatically caches dependencies to speed up future builds

    # MANDATORY FOR SINGLE-STAGE: Build the jar file manually
    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Login to Docker Hub
      shell: bash
      run: echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.REGISTRY_USERNAME }}" --password-stdin

    # Now Docker can build because target/app.jar exists
    - name: Build and Push Image
      shell: bash
      run: |
        docker build -t ${{ env.IMAGE_NAME }}:latest .
        docker push ${{ env.IMAGE_NAME }}:latest

